Update comradesFold2
Added svg plotting function

diff --git a/bin/comradesFold2 b/bin/comradesFold2
--- a/bin/comradesFold2
+++ b/bin/comradesFold2
@@ -5,8 +5,9 @@
 #generates RNA secondary structure of short- and long-range intramolecular- and intermolecular interactions and homodimers
 
 #example code
-#comradesFold2 -i ZAFR.hyb -1 ZAFR.fasta -x 3601 -y 5501 -l 500
-#input for folding between 3601-4100 and 5501-6000
+#comradesFold2 -i ZAFR.hyb -1 ZAFR.fasta -x 3601 -y 5501 -l 500 -j ~/bin/VARNA/build/jar/VARNAcmd.jar -0 1
+#input for folding between 3601-4100 and 5501-6000, and -0 1 activates interactive mode
+#to plot structure automatically as svg, omit -0 option
 
 #to only generate the inputs but not generating secondary structure, use:
 #separate scripts: lr_input.sh/inter_input.sh
@@ -16,7 +17,7 @@
 #LEN=length of fragment for folding
 
 # parsing command line options
-while getopts "i:a:b:1:2:x:y:l:" OPTION
+while getopts "i:a:b:1:2:x:y:l:j:0:" OPTION
 do
 	case $OPTION in
 		i) IN_FILE=$OPTARG ;;
@@ -27,6 +28,8 @@ do
 		x) X_COORD=$OPTARG ;;
 		y) Y_COORD=$OPTARG ;;
 		l) LEN=$OPTARG ;;
+		j) VARNA=$OPTARG ;;
+		0) INTERACTIVE=$OPTARG ;;
 		?) 
 
 		echo "incorrect option"
@@ -45,6 +48,13 @@ fi
 #Redirect input fasta as copied file in current directory
 FASTA_1=${FASTA_1##*/}
 FASTA_2=${FASTA_2##*/}
+
+#If Y_COORD specified larger than X_COORD for intramolecular folding, stop
+if [ -z $GENE_2 ] && [ "$X_COORD" -gt "$Y_COORD" ]
+then
+	echo 'Intramolecular Folding X_COORD must be lower than Y_COORD'
+	exit 1
+fi
 
 #Short-range intramolecular folding ---------------------------------------------------------------------------------------------------------------------
 #Set end coordinates and output file names
@@ -66,7 +76,7 @@ then
 	comradesMakeConstraints_2 -i $OUT_FILE -f $OUT_FASTA -b 1 -e $SPAN
 	comradesFold -c ${OUT_FILE/.hyb/.1-$(($SPAN))_folding_constraints.txt} -i $OUT_FASTA
 
-#Long-range intramolecular -----------------------------------------------------------------------------------------------------------
+#Long-range intramolecular / Homodimer folding -----------------------------------------------------------------------------------------------------------
 elif [ -z $GENE_2 ]
 then
 #defining start and end positions
@@ -83,12 +93,13 @@ then
 #extracting fasta sequence
 	awk '{if(NR==1) {print $0} else {if($0 ~ /^>/) {print "\n"$0} else {printf $0}}}' $FASTA_1 | grep -A1 $GENE_1 | awk -v b=$X1 -v e=$LEN '{if (/^>/) {print $1} else {print substr($0,b,e)}}' > $OUT_FASTA
 #padding
-        awk '{if(NR==1) {print $0} else {if($0 ~ /^>/) {print "\n"$0} else {printf $0}}}' $FASTA_1 | grep -A1 $GENE_1 | awk -v b=1 -v e=100 '{if (/^>/) {print $1} else {print substr($0,b,e)}}' >> $OUT_FASTA
+#        awk '{if(NR==1) {print $0} else {if($0 ~ /^>/) {print "\n"$0} else {printf $0}}}' $FASTA_1 | grep -A1 $GENE_1 | awk -v b=1 -v e=100 '{if (/^>/) {print $1} else {print substr($0,b,e)}}' >> $OUT_FASTA
+	echo 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT' >> $OUT_FASTA
 #2nd strand sequence
 	awk '{if(NR==1) {print $0} else {if($0 ~ /^>/) {print "\n"$0} else {printf $0}}}' $FASTA_1 | grep -A1 $GENE_1 | awk -v b=$Y1 -v e=$LEN '{if (/^>/) {print $1} else {print substr($0,b,e)}}' >> $OUT_FASTA
 
 #merging fasta sequence
-	awk 'NF' $OUT_FASTA | awk 'BEGIN{i=1}{line[i++]=$0}END{print line[1]"\n"line[2] line[4] line[6]}' > ${OUT_FASTA/.fasta/.tmp} && mv ${OUT_FASTA/.fasta/.tmp} $OUT_FASTA
+	awk 'NF' $OUT_FASTA | awk 'BEGIN{i=1}{line[i++]=$0}END{print line[1]"\n"line[2] line[3] line[5]}' > ${OUT_FASTA/.fasta/.tmp} && mv ${OUT_FASTA/.fasta/.tmp} $OUT_FASTA
 
 #folding
 	SPAN=$(($LEN+$LEN+100))
@@ -181,9 +192,36 @@ echo Top scoring structures:
 cat ${OUT_FILE/.hyb/_names_scores.txt} | sort -k2,2nr | head
 
 # display structure in VARNA:
-cat ${OUT_FILE/.hyb/_names_scores.txt} | sort -k2,2nr | head -n1 | while read name score; do vname=${name#*__} ; cat ${vname/.VARNA_scores.txt/.vienna}; echo Open ${vname/.VARNA_scores.txt/.vienna} in VARNA; done
+#cat ${OUT_FILE/.hyb/_names_scores.txt} | sort -k2,2nr | head -n1 | while read name score; do vname=${name#*__} ; cat ${vname/.VARNA_scores.txt/.vienna}; echo Open ${vname/.VARNA_scores.txt/.vienna} in VARNA for more customization options; done
+vname=$(cat ${OUT_FILE/.hyb/_names_scores.txt} | sort -k2,2nr | head -n1 | awk '{split($1,a,"__"); print a[2]}')
+name=$(cat ${OUT_FILE/.hyb/_names_scores.txt} | sort -k2,2nr | head -n1 | awk '{print $1}')
+cat ${vname/.VARNA_scores.txt/.vienna}; echo Open ${vname/.VARNA_scores.txt/.vienna} in VARNA for more customization options
 cat ${OUT_FILE/.hyb/_names_scores.txt} | sort -k2,2nr | head -n1 | while read name score; do awk '{print log($1)/log(2)}' $name | sed 's/-inf/0/g;s/^-.*/0/g' > ${name/_scores.txt/_log2scores.txt} ; echo Load ${name/_scores.txt/_log2scores.txt} as colour coding score in VARNA ; done
 
+echo "Plotting RNA Secondary Structure..."
+if [ "$INTERACTIVE" = "1" ]
+then
+	if [ -z $Y_COORD ]
+	then
+		plot_VARNA -i ${vname/.VARNA_scores.txt/.ct} -j $VARNA -s ${name/_scores.txt/_log2scores.txt} -x $X_COORD -l $LEN -0 1
+	else
+        	plot_VARNA -i ${vname/.VARNA_scores.txt/.ct} -j $VARNA -s ${name/_scores.txt/_log2scores.txt} -x $X_COORD -y $Y_COORD -l $LEN -0 1
+	fi
+else
+        if [ -z $Y_COORD ]
+        then
+                plot_VARNA -i ${vname/.VARNA_scores.txt/.ct} -j $VARNA -s ${name/_scores.txt/_log2scores.txt} -x $X_COORD -l $LEN
+        else
+                plot_VARNA -i ${vname/.VARNA_scores.txt/.ct} -j $VARNA -s ${name/_scores.txt/_log2scores.txt} -x $X_COORD -y $Y_COORD -l $LEN
+	fi
+fi
+
+if [ -f *${vname/.VARNA_scores.txt/_plot.svg} ]
+then
+	echo "Plotting Concluded"
+else
+	echo "Error! Something went wrong."
+fi
 
 echo "randomized parrallel RNA folding to fold RNA 1000 times using computer cluster:"
 echo "qsub comradesFold -c ${OUT_FILE/.hyb/.1-$(($SPAN))_folding_constraints.txt} -i $OUT_FASTA -s 1"
